// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: raritylist.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createRarity = `-- name: CreateRarity :one
INSERT INTO raritylist (id, created_at, updated_at, name)
VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, created_at, updated_at, name
`

type CreateRarityParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
}

func (q *Queries) CreateRarity(ctx context.Context, arg CreateRarityParams) (Raritylist, error) {
	row := q.db.QueryRowContext(ctx, createRarity,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Name,
	)
	var i Raritylist
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}

const raritylistReset = `-- name: RaritylistReset :exec
DELETE FROM raritylist
`

func (q *Queries) RaritylistReset(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, raritylistReset)
	return err
}
