// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: setlist.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createSet = `-- name: CreateSet :one
INSERT INTO setlist (id, created_at, updated_at, name)
VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, created_at, updated_at, name
`

type CreateSetParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
}

func (q *Queries) CreateSet(ctx context.Context, arg CreateSetParams) (Setlist, error) {
	row := q.db.QueryRowContext(ctx, createSet,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Name,
	)
	var i Setlist
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}

const setlistReset = `-- name: SetlistReset :exec
DELETE FROM setlist
`

func (q *Queries) SetlistReset(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, setlistReset)
	return err
}
