// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: setlist.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createSet = `-- name: CreateSet :one
INSERT INTO setlist (id, created_at, updated_at, name)
VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, created_at, updated_at, name
`

type CreateSetParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
}

func (q *Queries) CreateSet(ctx context.Context, arg CreateSetParams) (Setlist, error) {
	row := q.db.QueryRowContext(ctx, createSet,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Name,
	)
	var i Setlist
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}

const getSets = `-- name: GetSets :many
SELECT id, created_at, updated_at, name FROM setlist
`

func (q *Queries) GetSets(ctx context.Context) ([]Setlist, error) {
	rows, err := q.db.QueryContext(ctx, getSets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Setlist
	for rows.Next() {
		var i Setlist
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setlistReset = `-- name: SetlistReset :exec
DELETE FROM setlist
`

func (q *Queries) SetlistReset(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, setlistReset)
	return err
}
