// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sets.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createSetAndCard = `-- name: CreateSetAndCard :one
INSERT INTO sets (id, created_at, updated_at, name, card_id)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, created_at, updated_at, name, card_id
`

type CreateSetAndCardParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	CardID    uuid.UUID
}

func (q *Queries) CreateSetAndCard(ctx context.Context, arg CreateSetAndCardParams) (Set, error) {
	row := q.db.QueryRowContext(ctx, createSetAndCard,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Name,
		arg.CardID,
	)
	var i Set
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.CardID,
	)
	return i, err
}

const getCardsBySet = `-- name: GetCardsBySet :many
SELECT id, created_at, updated_at, name, card_id FROM sets WHERE name = $1
`

func (q *Queries) GetCardsBySet(ctx context.Context, name string) ([]Set, error) {
	rows, err := q.db.QueryContext(ctx, getCardsBySet, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Set
	for rows.Next() {
		var i Set
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.CardID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSetByCard = `-- name: GetSetByCard :one
SELECT id, created_at, updated_at, name, card_id FROM sets WHERE card_id = $1
`

func (q *Queries) GetSetByCard(ctx context.Context, cardID uuid.UUID) (Set, error) {
	row := q.db.QueryRowContext(ctx, getSetByCard, cardID)
	var i Set
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.CardID,
	)
	return i, err
}

const setsReset = `-- name: SetsReset :exec
DELETE FROM sets
`

func (q *Queries) SetsReset(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, setsReset)
	return err
}
